# Generated by Django 5.0 on 2024-01-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flairest_campus', '0002_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='inst/')),
                ('about', models.CharField(max_length=1000)),
                ('special', models.CharField(max_length=1000)),
                ('contacts', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=300)),
                ('about', models.CharField(max_length=2000)),
                ('special', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=1000)),
                ('passing_score_free', models.CharField(max_length=100)),
                ('passing_score_paid', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uni/')),
                ('about', models.CharField(max_length=2000)),
                ('contacts', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
    ]
