# Generated by Django 5.0 on 2024-01-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flairest_campus', '0004_remove_specialty_detail_remove_specialty_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='photo',
            field=models.ImageField(null=True, upload_to='spec/'),
        ),
    ]
